chore: Additional check for macOS
We need multipass on macOS to do signing

diff --git a/signing-common b/signing-common
--- a/signing-common
+++ b/signing-common
@@ -1,4 +1,12 @@
 #!/bin/sh
+case "$OSTYPE" in
+	"darwin"* )
+		[ $(command -v "multipass" | wc -l) -gt 0 ] || {
+			echo "Multipass is required to do signing from macOS!";
+			exit 1;
+		}
+	;;
+esac
 
 execute() {
 	OC_SIGNING_MULTIPASS_INSTANCE=${OC_SIGNING_MULTIPASS_INSTANCE:-"primary"}
